


default_connection_name = "advanced_data_engineering_snowflake"
[connections]
[connections.advanced_data_engineering_snowflake]
account = "ZIMSSPY-BWB76629"
user = "PASINDU"
password = "pasinduHPI90fait@"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
